apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "python-app-fastapi.fullname" . }}-configmap
data:
  MYSQL_HOST: {{ include "python-app-fastapi.fullname" . }}-mysql-service
  MYSQL_PORT: {{ .Values.configmap.MYSQL_PORT | quote }}
  MYSQL_USER: {{ .Values.configmap.MYSQL_USER | quote }}
  MYSQL_DATABASE: {{ .Values.configmap.MYSQL_DATABASE | quote }}