apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "python-app-fastapi.fullname" . }}-deployment
spec:
  {{- if not .Values.deployment.autoscaling.enabled }}
  replicas: {{ .Values.deployment.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "python-app-fastapi.selectorLabels" . | nindent 6 }}
      app: {{ .Values.labels.app.app }}
  template:
    metadata:
      labels:
        {{- include "python-app-fastapi.selectorLabels" . | nindent 8 }}
        app: {{ .Values.labels.app.app }}
    spec:
      initContainers:
      - name: delay-init-container
        image: alpine:latest
        command: ["sleep", "60"]
      containers:
      - name: python-app-fastapi-container
        image: {{ .Values.image.repository.app }}:{{ .Values.image.tag.app }}
        ports:
          - name: {{ .Values.deployment.app.ports.name }}
            containerPort: {{ .Values.deployment.app.ports.containerPort }}
          {{- if .Values.metrics.enabled }}
          - name: {{ .Values.metrics.svc.name }}
            containerPort: {{ .Values.metrics.svc.port }}
            protocol: TCP
          {{- end }}
        livenessProbe:
          httpGet:
            path: /health
            port: app-port
        readinessProbe:
          httpGet:
            path: /health
            port: app-port
        resources:
          {{- toYaml .Values.deployment.resources | nindent 12 }}
        env:
          - name: MYSQL_HOST
            valueFrom:
              configMapKeyRef:
                name: {{ include "python-app-fastapi.fullname" . }}-configmap
                key: MYSQL_HOST
          - name: MYSQL_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ include "python-app-fastapi.fullname" . }}-configmap
                key: MYSQL_PORT
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: {{ include "python-app-fastapi.fullname" . }}-configmap
                key: MYSQL_DATABASE
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                name: {{ include "python-app-fastapi.fullname" . }}-configmap
                key: MYSQL_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "python-app-fastapi.fullname" . }}-secret
                key: MYSQL_PASSWORD
            
