apiVersion: v1
kind: Service
metadata:
  name: {{ include "python-app-fastapi.fullname" . }}-service
  labels:
    {{- include "python-app-fastapi.labels" . | nindent 4 }}
    app: {{ .Values.labels.app.app }}
spec:
  type: {{ .Values.service.app.type }}
  ports:
    - port: {{ .Values.service.app.ports.port }}
      targetPort: {{ .Values.service.app.ports.targetPort }}
      protocol: {{ .Values.service.app.ports.protocol }}
      name: {{ .Values.service.app.ports.name }}
  selector:
    {{- include "python-app-fastapi.selectorLabels" . | nindent 4 }}
    app: {{ .Values.labels.app.app }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "python-app-fastapi.fullname" . }}-mysql-headless
  labels:
    {{- include "python-app-fastapi.labels" . | nindent 4 }}
    app: {{ .Values.labels.mysql.app }}
spec:
  ports:
    - port: {{ .Values.service.mysql.ports.port }}
      targetPort: {{ .Values.service.mysql.ports.targetPort }}
      protocol: {{ .Values.service.mysql.ports.protocol }}
      name: {{ .Values.service.mysql.ports.name }}
  type: ClusterIP
  clusterIP: None
  selector:
    {{- include "python-app-fastapi.selectorLabels" . | nindent 4 }}
    app: {{ .Values.labels.mysql.app }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "python-app-fastapi.fullname" . }}-mysql-service
  labels:
    {{- include "python-app-fastapi.labels" . | nindent 4 }}
    app: {{ .Values.labels.mysql.app }}
spec:
  type: {{ .Values.service.mysql.type }}
  ports:
    - port: {{ .Values.service.mysql.ports.port }}
      targetPort: {{ .Values.service.mysql.ports.targetPort }}
      protocol: {{ .Values.service.mysql.ports.protocol }}
      name: {{ .Values.service.mysql.ports.name }}
  selector:
    {{- include "python-app-fastapi.selectorLabels" . | nindent 4 }}
    app: {{ .Values.labels.mysql.app }}