apiVersion: v1
kind: Service
metadata:
  name: {{ include "python-app-fastapi.fullname" . }}-service
  labels:
    {{- include "python-app-fastapi.labels" . | nindent 4 }}
    app: {{ .Values.labels.app.app }}
spec:
  type: {{ .Values.service.app.type }}
  ports:
    - port: {{ .Values.service.app.ports.port }}
      targetPort: {{ .Values.service.app.ports.targetPort }}
      protocol: {{ .Values.service.app.ports.protocol }}
      name: {{ .Values.service.app.ports.name }}
    {{- if .Values.metrics.enabled }}
    - port: {{ .Values.metrics.svc.port }}
      targetPort: {{ .Values.metrics.svc.port }}
      protocol: {{ .Values.metrics.svc.protocol }}
      name: {{ .Values.metrics.svc.name }}
    {{- end }}
  selector:
    {{- include "python-app-fastapi.selectorLabels" . | nindent 4 }}
    app: {{ .Values.labels.app.app }}