{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "python-app-fastapi.fullname" . }}-sa
  labels:
    {{- include "python-app-fastapi.labels" . | nindent 4 }}
{{- end }}
