{{- if and .Values.metrics.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "python-app-fastapi.fullname"  . }}-sm
  labels:
    {{- include "python-app-fastapi.labels" . | nindent 4 }}
spec:
  endpoints:
  - port: {{ .Values.metrics.svc.name }}
  selector:
    matchLabels:
      {{- include "python-app-fastapi.selectorLabels" . | nindent 6 }}
{{- end }}
