on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

env:
  PYTHON_VERSION: '3.8.12'

name: Test
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Run MySQL container
        run: |
          docker rm -f docker_mysql
          docker run -d --name docker_mysql -p 3306:3306 -e MYSQL_ROOT_PASSWORD=password -e MYSQL_DATABASE=students mysql:latest
      
      - name: Checkout code
        uses: actions/checkout@v2

      - name: MySQL create table
        run: |
          docker exec -i docker_mysql mysql -uroot -ppassword students < students.sql
    
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Upgrade pip
        run: pip3 install --upgrade pip

      - name: Install python dependencies
        run: pip3 install -r requirements.txt

      - name: Run unit-tests
        run: pytest --cov