on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

env:
  PYTHON_VERSION: '3.8.12'
  MYSQL_VERSION: '8.2.0'
  MYSQL_ROOT_PASSWORD: 'password'
  MYSQL_DATABASE: 'students'

name: Test
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Run MySQL container
        run: |
          docker run -d --name docker_mysql -p 3306:3306 -e MYSQL_ROOT_PASSWORD=${{env.MYSQL_ROOT_PASSWORD}} -e MYSQL_DATABASE=${{env.MYSQL_DATABASE}} mysql:${{env.MYSQL_VERSION}}
      
      - name: Wait for MySQL to start
        run: |
          ./tools/check_mysql_ready.sh

      - name: MySQL create table
        run: |
          docker exec -i docker_mysql mysql -u root -p password students < students.sql
    
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Upgrade pip
        run: pip3 install --upgrade pip

      - name: Install python dependencies
        run: pip3 install -r requirements.txt

      - name: Run unit-tests
        run: pytest --cov
      
      - name: Destroy MySQL container
        run: docker rm -f docker_mysql