on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

env:
  PYTHON_VERSION: '3.8.12'

name: Test
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: students
        ports:
          - 3306:3306
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up MySQL database
        run: |
          echo "CREATE TABLE students (
                  id INT AUTO_INCREMENT PRIMARY KEY,
                  name VARCHAR(255) NOT NULL
                )" | mysql -h mysql -uroot -ppassword students

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Upgrade pip
        run: pip3 install --upgrade pip

      - name: Install python dependencies
        run: pip3 install -r requirements.txt

      - name: Run unit-tests
        run: pytest --cov