on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

env:
  PYTHON_VERSION: '3.8.12'
  MYSQL_VERSION: '8.2.0'
  MYSQL_HOST: 'docker_mysql'
  MYSQL_ROOT_PASSWORD: 'password'
  MYSQL_USER: 'studentsuser'
  MYSQL_PASSWORD: 'studentspassword'
  MYSQL_DATABASE: 'students'

name: Test-Python-App
jobs:
  Test-Python-App:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Run MySQL container
        run: |
          docker run -d --name $MYSQL_HOST -p 3306:3306 -e MYSQL_ROOT_PASSWORD=${{env.MYSQL_ROOT_PASSWORD}} -e MYSQL_USER=${{env.MYSQL_USER}} -e MYSQL_PASSWORD=${{env.MYSQL_PASSWORD}} -e MYSQL_DATABASE=${{env.MYSQL_DATABASE}} mysql:${{env.MYSQL_VERSION}}
      
      - name: Wait for MySQL to start
        run: |
          chmod +x ./tools/check_mysql_ready.sh
          ./tools/check_mysql_ready.sh
        shell: bash

      - name: MySQL create table
        run: |
          docker exec -i $MYSQL_HOST mysql -u$MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE < ./src/config/students.sql
    
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Upgrade pip
        run: pip3 install --upgrade pip

      - name: Install python dependencies
        run: pip3 install -r requirements.txt

      - name: Run unit-tests
        run: pytest --cov
      
      - name: Destroy MySQL container
        run: docker rm -f $MYSQL_HOST